### ISSUE TITLE
과제 Q2. 

### ISSUE THREAD

**Issue by bee85919** [yd3-team-parrots/bulls-and-cows#15]

**Comment by bee85919** [comment]
몬티 홀 시뮬레이션은 게임쇼 호스트인 몬티 홀의 유명한 문제를 시뮬레이션하는 실험입니다. 이 문제는 참가자가 선반에서 3개의 문 중 하나를 선택하고, 호스트가 참가자가 선택하지 않은 문 중 하나를 열어 문제를 바꿀지 유지할지 선택하게 만드는 문제입니다. 이 시뮬레이션은 이 문제를 반복해보며, 참가자가 선택을 바꿨을 때 이길 확률이 더 높은지를 보여줍니다.


1. 3개 중 하나를 선택  # 3개 중 하나가 보물
2. 보물이 아니며 플레이어가 고르지 않은 것을 확인
3. 선택을 바꿀 기회를 준다
4. 보물을 확인

**Comment by yuniwink** [comment]
https://hanana1253.github.io/2021/01/27/20210127_montyhall/

관련 코드 문서 링크 남깁니다 :-)
